ren W:\odoo\odoo-guides\odoo-guides\o13\ee\acc\o13-acc-accounting_guides.md o13-ee-acc-accounting_guides.md
ren W:\odoo\odoo-guides\odoo-guides\o13\ee\apr\o13-apr-appraisal_guides.md o13-ee-apr-appraisal_guides.md
ren W:\odoo\odoo-guides\odoo-guides\o13\ee\apt\o13-apt-appointments_guides.md o13-ee-apt-appointments_guides.md
ren W:\odoo\odoo-guides\odoo-guides\o13\ee\blg\o13-blg-blog_guides.md o13-ee-blg-blog_guides.md
ren W:\odoo\odoo-guides\odoo-guides\o13\ee\crm\o13-crm-crm_guides.md o13-ee-crm-crm_guides.md
ren W:\odoo\odoo-guides\odoo-guides\o13\ee\dsc\o13-dsc-discuss_guides.md o13-ee-dsc-discuss_guides.md
ren W:\odoo\odoo-guides\odoo-guides\o13\ee\eco\o13-eco-ecommerce_guides.md o13-ee-eco-ecommerce_guides.md
ren W:\odoo\odoo-guides\odoo-guides\o13\ee\emp\o13-emp-employees_guides.md o13-ee-emp-employees_guides.md
ren W:\odoo\odoo-guides\odoo-guides\o13\ee\equ\o13-equ-equipment_guides.md o13-ee-equ-equipment_guides.md
ren W:\odoo\odoo-guides\odoo-guides\o13\ee\esg\o13-esg-esignature_guides.md o13-ee-esg-esignature_guides.md
ren W:\odoo\odoo-guides\odoo-guides\o13\ee\eve\o13-eve-events_guides.md o13-ee-eve-events_guides.md
ren W:\odoo\odoo-guides\odoo-guides\o13\ee\exp\o13-exp-expenses_guides.md o13-ee-exp-expenses_guides.md
ren W:\odoo\odoo-guides\odoo-guides\o13\ee\flt\o13-flt-fleet_guides.md o13-ee-flt-fleet_guides.md
ren W:\odoo\odoo-guides\odoo-guides\o13\ee\for\o13-for-forum_guides.md o13-ee-for-forum_guides.md
ren W:\odoo\odoo-guides\odoo-guides\o13\ee\hdk\o13-hdk-helpdesk_guides.md o13-ee-hdk-helpdesk_guides.md
ren W:\odoo\odoo-guides\odoo-guides\o13\ee\inv\o13-inv-inventory_guides.md o13-ee-inv-inventory_guides.md
ren W:\odoo\odoo-guides\odoo-guides\o13\ee\iot\o13-iot-internet_of_things_guides.md o13-ee-iot-internet_of_things_guides.md
ren W:\odoo\odoo-guides\odoo-guides\o13\ee\ivc\o13-ivc-invoicing_guides.md o13-ee-ivc-invoicing_guides.md
ren W:\odoo\odoo-guides\odoo-guides\o13\ee\lch\o13-lch-live_chat_guides.md o13-ee-lch-live_chat_guides.md
ren W:\odoo\odoo-guides\odoo-guides\o13\ee\lea\o13-lea-leaves_guides.md o13-ee-lea-leaves_guides.md
ren W:\odoo\odoo-guides\odoo-guides\o13\ee\mka\o13-mka-marketing_automation_guides.md o13-ee-mka-marketing_automation_guides.md
ren W:\odoo\odoo-guides\odoo-guides\o13\ee\mnt\o13-mnt-maintenance_guides.md o13-ee-mnt-maintenance_guides.md
ren W:\odoo\odoo-guides\odoo-guides\o13\ee\mrp\o13-mrp-mrp_guides.md o13-ee-mrp-mrp_guides.md
ren W:\odoo\odoo-guides\odoo-guides\o13\ee\msm\o13-msm-mass_marketing_guides.md o13-ee-msm-mass_marketing_guides.md
ren W:\odoo\odoo-guides\odoo-guides\o13\ee\o13\o13-o13-system_wide_guides.md o13-ee-o13-system_wide_guides.md
ren W:\odoo\odoo-guides\odoo-guides\o13\ee\osh\o13-osh-odoo_sh_guides.md o13-ee-osh-odoo_sh_guides.md
ren W:\odoo\odoo-guides\odoo-guides\o13\ee\pch\o13-pch-purchasing_guides.md o13-ee-pch-purchasing_guides.md
ren W:\odoo\odoo-guides\odoo-guides\o13\ee\plm\o13-plm-plm_guides.md o13-ee-plm-plm_guides.md
ren W:\odoo\odoo-guides\odoo-guides\o13\ee\pos\o13-pos-point_of_sale_guides.md o13-ee-pos-point_of_sale_guides.md
ren W:\odoo\odoo-guides\odoo-guides\o13\ee\pro\o13-pro-projects_guides.md o13-ee-pro-projects_guides.md
ren W:\odoo\odoo-guides\odoo-guides\o13\ee\rcr\o13-rcr-recruitment_guides.md o13-ee-rcr-recruitment_guides.md
ren W:\odoo\odoo-guides\odoo-guides\o13\ee\skm\o13-skm-skills_management_guides.md o13-ee-skm-skills_management_guides.md
ren W:\odoo\odoo-guides\odoo-guides\o13\ee\sli\o13-sli-slides_guides.md o13-ee-sli-slides_guides.md
ren W:\odoo\odoo-guides\odoo-guides\o13\ee\sls\o13-sls-sales_guides.md o13-ee-sls-sales_guides.md
ren W:\odoo\odoo-guides\odoo-guides\o13\ee\stu\o13-stu-studio_guides.md o13-ee-stu-studio_guides.md
ren W:\odoo\odoo-guides\odoo-guides\o13\ee\sub\o13-sub-subscriptions_guides.md o13-ee-sub-subscriptions_guides.md
ren W:\odoo\odoo-guides\odoo-guides\o13\ee\svy\o13-svy-survey_guides.md o13-ee-svy-survey_guides.md
ren W:\odoo\odoo-guides\odoo-guides\o13\ee\tsh\o13-tsh-timesheet_guides.md o13-ee-tsh-timesheet_guides.md
ren W:\odoo\odoo-guides\odoo-guides\o13\ee\web\o13-web-websites_builder_guides.md o13-ee-web-websites_builder_guides.md
